services:
  caddy:
    image: caddy:alpine
    restart: always
    ports:
      - "3070:3070"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
      - frontend

  app:
    build: .
    restart: always
    expose:
      - "3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_PORT=5432
      - PORT=3000
    command: npm start

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    restart: always
    expose:
      - "80"
    depends_on:
      - app

volumes:
  pgdata:
  caddy_data:
  caddy_config:
